export enum ACTION {
    ADD_TO_WISHLIST = 'ADD_TO_WISHLIST',
    ADD_TO_CART = 'ADD_TO_CART',
    DELETE_FROM_WISHLIST = 'DELETE_FROM_WISHLIST',
    DELETE_FROM_CART = 'DELETE_FROM_CART',
    USER_UPDATE = 'USER_UPDATE',
}
