export enum ACTION {
    ADD_TO_WISHLIST = 'ADD_TO_WISHLIST',
    ADD_TO_CART = 'ADD_TO_CART',
    ADD_TO_BAG = 'ADD_TO_BAG',
    DELETE_FROM_WISHLIST = 'DELETE_FROM_WISHLIST',
    DELETE_FROM_CART = 'DELETE_FROM_CART',
    USER_UPDATE = 'USER_UPDATE',
    UPDATE_COUNT_IN_BAG = 'UPDATE_COUNT_IN_BAG',
    SWITCH_THEME = 'SWITCH_THEME',
    SIGN_UP_WITH_GOOGLE = 'SIGN_UP_WITH_GOOGLE',
    SIGN_UP = 'SIGN_UP',
}
